using ASP_MVC_01.Models;

namespace ASP_MVC_01.Services {
    public class PlanetService : List<PlanetModel> {
        public PlanetService(){
            this.AddRange(new PlanetModel[]{
                new PlanetModel() {Id=1, Name = "Jupiter", VnName = "Sao Mộc", Content="Jupiter is the largest planet in the solar system. It’s about 11 times wider than Earth with an equatorial diameter of 88,846 miles (about 142,984 kilometers). Jupiter is the fifth planet from the Sun, orbiting at an average distance of 483.7 million miles (778 million kilometers). It’s about five times farther from the Sun than Earth."},
                new PlanetModel() {Id=2, Name = "Saturn", VnName = "Sao Thổ", Content="Saturn, known for its spectacular icy rings, is the second largest planet in our solar system. It’s about nine times wider than Earth, with an equatorial diameter of about 74,898 miles (about 120,536 kilometers). Saturn is the sixth planet from the Sun, orbiting at an average distance of 889.8 million miles (1.4 billion kilometers). It’s about 9.5 times farther from the Sun than Earth."},
                new PlanetModel() {Id=3, Name = "Uranus", VnName = "Sao Thiên Vương", Content="Uranus is the third largest planet in our solar system. It’s about four times wider than Earth, and has an equatorial diameter of about 31,763 miles (51,118 kilometers). Uranus is the seventh planet from the Sun, orbiting at an average distance of 1.8 billion miles (2.9 billion kilometers). It’s about 19 times farther from the Sun than Earth. "},
                new PlanetModel() {Id=4, Name = "Neptune", VnName = "Hải Vương Tinh", Content="Neptune is the fourth largest planet. It’s about four times wider than Earth with an equatorial diameter of about 30,775 miles (49,528 kilometers). Neptune is the eighth, and the most distant planet from the Sun, orbiting at an average distance of 2.8 billion miles (4.5 billion kilometers). Neptune is about 30 times farther from the Sun than Earth. "},
                new PlanetModel() {Id=5, Name = "Earth", VnName = "Trái Đất", Content="Earth is the fifth largest planet in the solar system. It has an equatorial diameter of about 7,926 miles (12,756 kilometers). Earth is the third planet from the Sun, orbiting at an average distance of 93 million miles (149.7 million kilometers)."},
                new PlanetModel() {Id=6, Name = "Venus", VnName = "Sao Kim", Content="Venus is the sixth largest planet in the solar system. Venus is about the same width as Earth, and has an equatorial diameter of about 7,521 miles (12,104 kilometers). For this reason, Venus is sometimes known as Earth’s twin. Venus is the second planet from the Sun, orbiting at an average distance of 67.2 million miles (108 million kilometers). Venus is about 26 million miles (42 million kilometers) closer to the Sun than Earth. "},
                new PlanetModel() {Id=7, Name = "Mars", VnName = "Sao Hỏa", Content="Mars, the red planet, is the seventh largest planet in our solar system. Mars is about half the width of Earth, and has an equatorial diameter of about 4,221 miles (6,792 kilometers). Mars is the fourth planet from the Sun, orbiting at an average distance of 141.6 million miles (227.9 million kilometers). Mars is about 49 million miles (79 million kilometers) farther from the Sun than Earth."},
                new PlanetModel() {Id=8, Name = "Mercury", VnName = "Sao Thủy", Content="Mercury is the smallest planet in our solar system. Mercury is a little more than one-third the width of Earth, and has an equatorial diameter of about 3,032 miles (4,880 kilometers). Mercury is the closest planet to the Sun, orbiting at an average distance of 36 million miles (58 million kilometers). Mercury is 57 million miles closer to the Sun than Earth."},
            });
        }
    }
}